[[LA]]
sound = "global_street_ambience.mp3"
gain = 0.2

[[LA]]
sound = "WindExternal.wav"
x = 0
y = 0
z = 2

[[LA]]
sound = "SirenSlow.wav"
x = 10
y = 10
z = 2
refDistance = 2
rolloffFactor = 1
gain = 2
coneInnerAngle = 90
coneOuterAngle = 180
coneOuterGain = 0
rotation = 90
