[insim]
host = "127.0.0.1"
port = 29999
admin = ''

[sounds]
BL = [
  { x = 1, y = 2, z = 3, sound = 'bla.wav' },
  { x = 1333, y = 222, z = 43, sound = 'bla2.wav' }
]
FE = [

]
SO = [

]
AU = [

]
KY = [

]
AS = [

]
WE = [

]
RO = [

]
LA = [
  { x = 0, y = 0, z = 2, sound = 'ambi.wav' }
]